### ISSUE TITLE
FileNotFoundError: No such file: '/media/hhy/Ventoy/xbd/train/images/hurricane-florence_00000263_pre_disaster_pre_disaster.png.png'

### ISSUE THREAD

**Issue by XiaoBaiHhy** [ChenHongruixuan/MambaCD#18]
Hello, I am trying to execute the BDA task and ran train-MambaBDA.py. The following error occurred. I thought it was a problem with the dataset, but I downloaded the xbd dataset again and still encountered the same problem. Can you help me answer this? In addition, I saw that the hold out data, which is not useful for executing BDA tasks, was used there?
I also encountered the same problem when running the train-Mambascd.py file.

  parser.add_argument('--pretrained_weight_path', type=str,default='/home/hhy/下载/MambaCD-master/pretrained_weight/vssm_small_0229_ckpt_epoch_222.pth'
                                                                     '')

    parser.add_argument('--dataset', type=str, default='xBD')
    parser.add_argument('--type', type=str, default='train')
    parser.add_argument('--train_dataset_path', type=str, default='/media/hhy/Ventoy/xbd/train')
    parser.add_argument('--train_data_list_path', type=str, default='/media/hhy/Ventoy/xbd/train/train.txt')
    parser.add_argument('--test_dataset_path', type=str, default='/media/hhy/Ventoy/xbd/test')
    parser.add_argument('--test_data_list_path', type=str, default='/media/hhy/Ventoy/xbd/test/test.txt')
    parser.add_argument('--shuffle', type=bool, default=True)
    parser.add_argument('--batch_size', type=int, default=4)
    parser.add_argument('--crop_size', type=int, default=256)
    parser.add_argument('--train_data_name_list', type=list)
    parser.add_argument('--test_data_name_list', type=list)
    parser.add_argument('--start_iter', type=int, default=0)
    parser.add_argument('--cuda', type=bool, default=True)
    parser.add_argument('--max_iters', type=int, default=800000)
    parser.add_argument('--model_type', type=str, default='bda——small')
    parser.add_argument('--model_param_path', type=str, default='../saved_models')

    parser.add_argument('--resume', type=str)
    parser.add_argument('--learning_rate', type=float, default=1e-4)
    parser.add_argument('--momentum', type=float, default=0.9)
    parser.add_argument('--weight_decay', type=float, default=5e-3)

False
  0%|          | 0/200000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hhy/下载/MambaCD-master/changedetection/script/train_MambaBDA.py", line 235, in <module>
    main()
  File "/home/hhy/下载/MambaCD-master/changedetection/script/train_MambaBDA.py", line 231, in main
    trainer.training()
  File "/home/hhy/下载/MambaCD-master/changedetection/script/train_MambaBDA.py", line 97, in training
    itera, data = train_enumerator.__next__()
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hhy/下载/MambaCD-master/changedetection/datasets/make_data_loader.py", line 189, in __getitem__
    pre_img = self.loader(pre_path)
  File "/home/hhy/下载/MambaCD-master/changedetection/datasets/make_data_loader.py", line 14, in img_loader
    img = np.array(imageio.imread(path), np.float32)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/home/hhy/anaconda3/envs/mamba/lib/python3.9/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/media/hhy/Ventoy/xbd/train/images/hurricane-florence_00000263_pre_disaster_pre_disaster.png.png'

**Comment by ChenHongruixuan** [comment]
Hi, 

Please see the last line. Check the filename you wrote in your txt file and compatibility with the dataloder code, as dataloder will automatically add the suffix.

For the example shown, in my txt file I wrote [hurricane-florence_00000263] and the dataloader automatically adds the [_pre_disaster.png] suffix.

Best,

**Comment by XiaoBaiHhy** [comment]
thanks

**Comment by kuaiqushangzixiba** [comment]
Has the holdout data been used?
