### ISSUE TITLE
 AssertionError 

### ISSUE THREAD

**Issue by chartgod** [ChenHongruixuan/MambaCD#63]
AssertionErrorThe corresponding error has occurred,

checkpoint = torch.load(args.resume)
Traceback (most recent call last):
File "/home/lsh/share/MambaCD/changedetection/script/infer_MambaBCD_test1.py", line 163, in <module>
main()
File "/home/lsh/share/MambaCD/changedetection/script/infer_MambaBCD_test1.py", line 159, in main
infer.infer()
File "/home/lsh/share/MambaCD/changedetection/script/infer_MambaBCD_test1.py", line 105, in infer
self.evaluator.add_batch(labels, output_1)
File "/home/lsh/share/MambaCD/changedetection/utils_func/metrics.py", line 100, in add_batch
assert gt_image.shape == pre_image.shape

How can I solve the above problem?

**Comment by ChenHongruixuan** [comment]
Hi @chartgod ,

The issue had not been raised before by all the peers. Have you modified our code or run it on your own dataset? 

Based on the error info, it appears to be caused by an inconsistency in size between labels and the network predictions. You can Debug to see the specific reason.

Please kindly consider giving this repository a star if our code helps you in your research, thank you very much!

Best,

**Comment by chartgod** [comment]
When outputting the predicted binary image, the dimensions were different from label.shape and output.shape, so it was corrected by modifying it to two dimensions and making it grayscale.
