### ISSUE TITLE
RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by earnestworthing** [ChenHongruixuan/MambaCD#83]
Dear author,

When I try to run the building damage assessment script `changedetection/script/train_MambaBDA.py` with the following setup:
>torch: 2.2.0, torchvision: 0.17.0, cuda: 11.8

>Dataloader output shape: pre_img: (3, 256, 256), post_img: (3, 256, 256), loc_label: (256, 256), clf_label: (256, 256); whereby loc_label is in [0,1] and clf_label in [0,1,2,3,4]

 I get the following error:

`Traceback (most recent call last):
  File` "/somepath/MambaCD/changedetection/script/train_MambaBDA.py", line 235, in <module>
    main()
  File "/somepath/MambaCD/changedetection/script/train_MambaBDA.py", line 231, in main
    trainer.training()
  File "/somepath/MambaCD/changedetection/script/train_MambaBDA.py", line 111, in training
    output_loc, output_clf = self.deep_model(pre_change_imgs, post_change_imgs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/changedetection/models/STMambaBDA.py", line 84, in forward
    pre_features = self.encoder(pre_data)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/changedetection/models/Mamba_backbone.py", line 50, in forward
    o, x = layer_forward(layer, x) # (B, H, W, C)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/changedetection/models/Mamba_backbone.py", line 43, in layer_forward
    x = l.blocks(x)
        ^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 1360, in forward
    return self._forward(input)
           ^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 1348, in _forward
    x = input + self.drop_path(self.op(self.norm(input)))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 1147, in forwardv2
    y = self.forward_core(x)
        ^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 1124, in forward_corev2
    return cross_selective_scan(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 406, in cross_selective_scan
    ys: torch.Tensor = selective_scan(
                       ^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 372, in selective_scan
    return SelectiveScan.apply(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows, backnrows, ssoflex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/myuser/mambaforge/envs/changemamba/lib/python3.11/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/somepath/MambaCD/classification/models/vmamba.py", line 299, in forward
    out, x, *rest = selective_scan_cuda_oflex.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, 1, oflex)
    
RuntimeError: Unknown layout`
    
   Could you please help me further?
   
   Thank you very much for your efforts in advance.

**Comment by ChenHongruixuan** [comment]
Hi @earnestworthing ,

Thank you for your question. Could you confirm that you have successfully installed the VMamba libraries? It seems that the problem was caused by the scan part of VMamba. 

Best,
