### ISSUE TITLE
scd valid error

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [ChenHongruixuan/MambaCD#92]
Traceback (most recent call last):
  File "/data/MambaCD/changedetection/script/train_MambaSCD.py", line 263, in <module>
    main()
  File "/data/MambaCD/changedetection/script/train_MambaSCD.py", line 259, in main
    trainer.training()
  File "/data/MambaCD/changedetection/script/train_MambaSCD.py", line 149, in training
    kappa_n0, Fscd, IoU_mean, Sek, oa = self.validation()
                                        ^^^^^^^^^^^^^^^^^
  File "/data/MambaCD/changedetection/script/train_MambaSCD.py", line 199, in validation
    acc_A, valid_sum_A = accuracy(pred_scd, label_scd)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/MambaCD/changedetection/utils_func/mcd_utils.py", line 176, in accuracy
    acc_sum = (valid * (pred == label)).sum()
                        ^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (512,512) (512,512,3)

**Comment by ChenHongruixuan** [comment]
Hi @kuaiqushangzixiba ,

Thank you so much for your question. Please preprocess the SECOND dataset as according to our README file. Or you can download our preprocessed SECOND dataset.

Best,
